# -*- coding: utf-8 -*-

DEBUG=False

REDIS_HOST="10.168.188.86"
REDIS_PORT=6380
REDIS_DB=0
REDIS_PASSWORD=""

MYSQL_HOST = "rdsme36vin2uqrn.mysql.rds.aliyuncs.com"
MYSQL_PORT = 3306
MYSQL_AUTOCOMMIT = True
MYSQL_CHARSET = 'utf8'

MYSQL_USER = "lace_new"
MYSQL_PASSWD = "123456"


MYSQL_IM_DATABASE = "gobelieve"
MYSQL_GB_DATABASE = "gobelieve"


# host,port,user,password,db,auto_commit,charset
MYSQL_IM = (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWD, MYSQL_IM_DATABASE, MYSQL_AUTOCOMMIT, MYSQL_CHARSET)

MYSQL = (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWD, MYSQL_GB_DATABASE, MYSQL_AUTOCOMMIT, MYSQL_CHARSET)


FS_HOST="10.251.43.254"
FS_PORT=8888

IM_RPC_URL = "http://10.251.43.254:7777"

