#!/bin/sh
project="im_api"
app_dir="/data/wwwroot/${project}"
log_dir="/data/logs/${project}"
image="im_python_dev"

cd ${app_dir} || exit
unset GIT_DIR
git pull

cp -f pro_config/config.py ./config.py

mkdir -p ${log_dir}

docker restart ${project} || docker run -d --restart=always --name=${project} --net=host -v ${log_dir}:/logs  -v ${app_dir}/pro_config/supervisord.conf:/etc/supervisord.conf -v ${app_dir}:/app ${image} /usr/local/python/bin/supervisord

